"""Portfolio universe metadata used by analysis and deployment."""

THEME_BY_TICKER = {
    "ASML": "Semiconductors",
    "AVGO": "Semiconductors",
    "TSM": "Semiconductors",
    "MSFT": "Platforms",
    "GOOGL": "Platforms",
    "LLY": "Pharma",
    "NVO": "Pharma",
    "ISRG": "MedTech",
    "UNH": "Managed Care",
    "JPM": "Banks",
    "SPGI": "Data & Analytics",
    "RELX": "Data & Analytics",
    "ROP": "Vertical Software",
    "TDG": "Aerospace",
    "LIN": "Industrial Gases",
    "EQIX": "Real Estate",
    "PLD": "Real Estate",
}

FINANCIAL_TICKERS = {"JPM"}

# Wide-moat compounders to screen as potential additions (not currently held).
# Each entry maps ticker to (display name, theme).
CANDIDATE_UNIVERSE = {
    "V": ("Visa Inc", "Payments"),
    "MA": ("Mastercard Inc", "Payments"),
    "COST": ("Costco Wholesale", "Consumer Staples"),
    "NVDA": ("NVIDIA Corporation", "Semiconductors"),
    "AAPL": ("Apple Inc", "Platforms"),
    "AMZN": ("Amazon.com Inc", "Platforms"),
    "META": ("Meta Platforms Inc", "Platforms"),
    "LVMUY": ("LVMH Moet Hennessy Louis Vuitton ADR", "Luxury"),
    "RACE": ("Ferrari NV", "Luxury"),
    "ADBE": ("Adobe Inc", "Vertical Software"),
    "NOW": ("ServiceNow Inc", "Vertical Software"),
    "INTU": ("Intuit Inc", "Vertical Software"),
    "ORCL": ("Oracle Corporation", "Enterprise Software"),
    "SAP": ("SAP SE ADR", "Enterprise Software"),
    "CRM": ("Salesforce Inc", "Enterprise Software"),
    "ACN": ("Accenture plc", "IT Services"),
    "MCO": ("Moody's Corporation", "Data & Analytics"),
    "MSCI": ("MSCI Inc", "Data & Analytics"),
    "ICE": ("Intercontinental Exchange Inc", "Data & Analytics"),
    "CME": ("CME Group Inc", "Data & Analytics"),
    "HD": ("Home Depot Inc", "Retail"),
    "LOW": ("Lowe's Companies Inc", "Retail"),
    "TJX": ("TJX Companies Inc", "Retail"),
    "CTAS": ("Cintas Corporation", "Industrials"),
    "WM": ("Waste Management Inc", "Essential Services"),
    "WCN": ("Waste Connections Inc", "Essential Services"),
    "ITW": ("Illinois Tool Works Inc", "Industrials"),
    "SHW": ("Sherwin-Williams Company", "Specialty Materials"),
    "APD": ("Air Products and Chemicals Inc", "Industrial Gases"),
    "DE": ("Deere & Company", "Industrial Equipment"),
    "SNPS": ("Synopsys Inc", "Vertical Software"),
    "CDNS": ("Cadence Design Systems", "Vertical Software"),
    "ANET": ("Arista Networks", "Networking"),
    "TXN": ("Texas Instruments Inc", "Semiconductors"),
    "EW": ("Edwards Lifesciences Corporation", "MedTech"),
    "ODFL": ("Old Dominion Freight Line", "Industrials"),
    "VICI": ("VICI Properties Inc", "Real Estate"),
    "O": ("Realty Income Corp", "Real Estate"),
    "AMT": ("American Tower Corp", "Real Estate"),
    "EQNR": ("Equinor ASA ADR", "Energy"),
    "ENB": ("Enbridge Inc", "Energy Infrastructure"),
}
